server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
  zipkin:
    baseUrl: http://zipkin:9411/

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true
